version 8.0.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2579,6 +2579,18 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+# Find the compiler and compiler flags to use
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+    echo "could not determine R_HOME"
+    exit 1
+fi
+RBIN="${R_HOME}/bin/R"
+RSCRIPT="${R_HOME}/bin/Rscript"
+RBIN_CPPFLAGS=`"${RBIN}" CMD config CPPFLAGS`
+CPPFLAGS="${CPPFLAGS} ${RBIN_CPPFLAGS}"
+LIBS="${LIBS}"
+
 # Check for OpenMP
 
 
@@ -2647,23 +2659,17 @@ $as_echo "$ac_cv_prog_c_openmp" >&6; }
   fi
 
 
-
-# Find the compiler and compiler flags to use
-: ${R_HOME=`R RHOME`}
-if test -z "${R_HOME}"; then
-    echo "could not determine R_HOME"
-    exit 1
-fi
-RBIN="${R_HOME}/bin/R"
-RSCRIPT="${R_HOME}/bin/Rscript"
-RBIN_CPPFLAGS=`"${RBIN}" CMD config CPPFLAGS`
-CPPFLAGS="${CPPFLAGS} ${RBIN_CPPFLAGS}"
-LIBS="${LIBS}"
-
-# since some systems have broken OMP libraries
-# we also check that the actual package will work
 ac_pkg_openmp=no
-if test -n "${OPENMP_CFLAGS}"; then
+if test "x$enable_openmp" != "xno"; then
+    # Since some systems have broken OpenMP libraries we also check
+    # that the actual package will work.
+
+    if test -z "${OPENMP_CFLAGS}"; then
+        # OpenMP was not detected by the macro AC_OPENMP, try forcing
+        # -fopenmp instead.
+        OPENMP_CFLAGS="-fopenmp"
+    fi
+
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether OpenMP will work in a package" >&5
 $as_echo_n "checking whether OpenMP will work in a package... " >&6; }
     cat confdefs.h - <<_ACEOF >conftest.$ac_ext
@@ -2677,17 +2683,17 @@ main ()
   return 0;
 }
 _ACEOF
-    PKG_CFLAGS="${OPENMP_CFLAGS}" PKG_LIBS="${OPENMP_CFLAGS}" "$RBIN" CMD SHLIB conftest.c \
+    PKG_CFLAGS="${OPENMP_CFLAGS}" PKG_LIBS="${OPENMP_CFLAGS}" \
+    "$RBIN" CMD SHLIB conftest.c \
     1>&5 2>&5 && \
     "$RBIN" --vanilla -q -e "dyn.load(paste('conftest',.Platform\$dynlib.ext,sep=''))" \
     1>&5 2>&5 && ac_pkg_openmp=yes
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: ${ac_pkg_openmp}" >&5
 $as_echo "${ac_pkg_openmp}" >&6; }
-fi
 
-if test "x${ac_pkg_openmp}" = xno; then
-    OPENMP_CFLAGS=''
-    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING:
+    if test "x${ac_pkg_openmp}" = xno; then
+        OPENMP_CFLAGS=''
+        { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING:
   -----------------------------------------------
    Unable to find OpenMP on this system.
    Building a version without support for OpenMP.
@@ -2697,6 +2703,12 @@ $as_echo "$as_me: WARNING:
    Unable to find OpenMP on this system.
    Building a version without support for OpenMP.
   -----------------------------------------------" >&2;}
+    fi
+else
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether to use OpenMP" >&5
+$as_echo_n "checking whether to use OpenMP... " >&6; }
+    { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
 fi
 
 # Check for gsl
@@ -2748,7 +2760,7 @@ if test "x${GSL_CONFIG}" != x; then
     have_gsl=yes
 else
     # Check for gsl using autoconf macros
-    # https://www.gnu.org/software/gsl/manual/html_node/Autoconf-Macros.html
+    # https://www.gnu.org/software/gsl/doc/html/autoconf.html
     { $as_echo "$as_me:${as_lineno-$LINENO}: checking for cos in -lm" >&5
 $as_echo_n "checking for cos in -lm... " >&6; }
 if ${ac_cv_lib_m_cos+:} false; then :
@@ -2916,9 +2928,9 @@ fi
 # List all model files to compile
 MODELS_OBJ=`"${RSCRIPT}" --slave --vanilla -e "cat(paste0('models/', sub('c$', 'o', list.files('src/models', '.c$')), collapse=' '))"`
 
-PKG_CPPFLAGS="-I. -Imisc -Imodels ${CPPFLAGS} ${GSL_CFLAGS}"
+PKG_CPPFLAGS="-I. -Imisc -Imodels ${CPPFLAGS} ${GSL_CFLAGS} -DR_NO_REMAP -DSTRICT_R_HEADERS"
 
-PKG_CFLAGS="${OPENMP_CFLAGS} -DR_NO_REMAP -DSTRICT_R_HEADERS"
+PKG_CFLAGS="${OPENMP_CFLAGS}"
 
 PKG_LIBS="${OPENMP_CFLAGS} ${GSL_LIBS} ${LIBS}"
 
@@ -2930,9 +2942,9 @@ ac_config_files="$ac_config_files src/Makevars"
 echo "
   ---- Results for the SimInf package configure ----
 
-    PKG_CPPFLAGS..............: -I. -Imisc -Imodels ${CPPFLAGS} ${GSL_CFLAGS}
-    PKG_LIBS..................: ${OPENMP_CFLAGS} ${GSL_LIBS} ${LIBS}
-    PKG_CFLAGS................: ${OPENMP_CFLAGS} -DR_NO_REMAP -DSTRICT_R_HEADERS
+    PKG_CPPFLAGS..............: ${PKG_CPPFLAGS}
+    PKG_CFLAGS................: ${PKG_CFLAGS}
+    PKG_LIBS..................: ${PKG_LIBS}
     Have support for OpenMP...: ${ac_pkg_openmp}
 
   --------------------------------------------------
